global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets: [
        'weibotrending-b30ef36332fe.herokuapp.com' ,
        'wtafull-6e96b8af91e4.herokuapp.com'
      ]
